#!/bin/bash

echo 'install docker'
sudo apt-get install docker.io

echo 'install docker-compose'
sudo curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
